apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: first-kubernetes-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: dokkaushik/mock:latest #dokkaushik/backend:latest  # replace with your actual Docker image
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
