apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: property-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/KaranamSaiKrishnaKaushik/first-kubernetes-app
    targetRevision: HEAD
    path: k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: first-kubernetes-app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
