apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-app-k8s
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/KaranamSaiKrishnaKaushik/my-app-k8s
    targetRevision: HEAD
    path: k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: my-app-k8s
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
