services:
  frontend:
    build: ./my-angular-app
    image: frontend-kube
    ports:
      - "4200:80"
    depends_on:
      - backend

  backend:
    build: ./Mock
    image: backend-kube
    ports:
      - "5000:8080"