name: CI/CD Pipeline

on:
  push:
    branches:
      - main

env:
  REGISTRY: docker.io
  DOCKER_USERNAME: dokkaushik  # your Docker Hub username
  IMAGE_TAG: main              # constant tag used by Argo CD

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        
    - name: Show directory structure
      run: ls -R
      
    - name: Print working directory
      run: pwd
      
    - name: Build and Push Frontend Image
      run: |
        docker build -t $REGISTRY/${{ env.DOCKER_USERNAME }}/my-angular-app:${{ env.IMAGE_TAG }} ./my-angular-app
        docker push $REGISTRY/${{ env.DOCKER_USERNAME }}/my-angular-app:${{ env.IMAGE_TAG }}

    - name: Build and Push Backend Image
      run: |
        docker build -t $REGISTRY/${{ env.DOCKER_USERNAME }}/mock-api:${{ env.IMAGE_TAG }} ./Mock
        docker push $REGISTRY/${{ env.DOCKER_USERNAME }}/mock-api:${{ env.IMAGE_TAG }}
