name: CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: dokkaushik
        password: Iamthebest
    - name: Debug - Show Files
      run: |
        pwd
        ls -R

    - name: Build and Push Frontend
      run: |
        docker build -t dokkaushik/my-angular-app ./my-angular-app
        docker push dokkaushik/my-angular-app

    - name: Build and Push Backend
      run: |
        docker build -t dokkaushik/mock ./Mock
        docker push dokkaushik/mock
        
    - name: Update image tag in web-deployment.yaml
      run: |
          sed -i "s|image: dokkaushik/my-angular-app:.*|image: dokkaushik/my-angular-app:${{ github.sha }}|" k8s/dev/web-deployment.yaml
    
    - name: Update image tag in api-deployment.yaml
      run: |
          sed -i "s|image: dokkaushik/mock:.*|image: dokkaushik/mock:${{ github.sha }}|" k8s/dev/api-deployment.yaml
          
    - name: Set up Git for commit
      run: |
        git config --global user.email "ci-bot@github.com"
        git config --global user.name "CI Bot"

    - name: Commit and Push Updated Deployment YAMLs
      env:
        GH_PAT: ${{ secrets.GH_PAT }}
      run: |
        git add k8s/dev/web-deployment.yaml k8s/dev/api-deployment.yaml
        git commit -m "Update image tags to ${{ github.sha }}" || echo "No changes to commit"
        git remote set-url origin https://x-access-token:${GH_PAT}@github.com/${{ github.repository }}
        git push origin main 
    